
services:
  joplin_server:
    image: ${image}
    container_name: 'joplin_server'
    restart: ${restart}
    ports: 
      - ${port}:80
    volumes: 
      - /etc/localtime:/etc/localtime
    # command: ["sleep", "10m"]         # 调试问题打开用
    environment:
      MAX_TIME_DRIFT: 0     # 这个设置为禁止 ntp 时间检验，在只有内网时一定要设置
      APP_PORT: 80          # 监听端口
      APP_BASE_URL:         # 外网访问地地址(如果有代理也要与外网的强一到)
      DB_CLIENT: pg
      POSTGRES_HOST:        # postgres 地址
      POSTGRES_PORT:        # postgres 端口
      POSTGRES_USER:        # postgres 用户
      POSTGRES_DATABASE:    # postgres 库名
      POSTGRES_PASSWORD:    # postgres 密码
    networks:
      net-custom:
        # ipv4_address:     # 指定 ip
        aliases: 
          - net-joplin_server


networks: 
  net-custom:
    name: ${network}
    external: true 


